name: Solr Tests

on:
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  test:
    name: Run Solr Tests using Crave.io resources

    runs-on: ubuntu-latest

    env:
      GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GE_ACCESS_TOKEN }}
      GRADLE_ENTERPRISE_URL: https://ge.solutions-team.gradle.com

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Generate crave.yml
      run: |
        echo "Solr:" > crave.yml
        echo "  env:" >> crave.yml
        echo "    CI: true" >> crave.yml
        echo "    GITHUB_SERVER_URL: $GITHUB_SERVER_URL" >> crave.yml
        echo "    GITHUB_REPOSITORY: $GITHUB_REPOSITORY" >> crave.yml
        echo "    GITHUB_RUN_ID: $GITHUB_RUN_ID" >> crave.yml
        echo "    GITHUB_WORKFLOW: $GITHUB_WORKFLOW" >> crave.yml
        cat crave.yml
    - run: git remote set-url origin git@github.com:apache/solr.git
    - name: Get the Crave binary
      run: curl -s https://raw.githubusercontent.com/accupara/crave/master/get_crave.sh | bash -s --
    - name: Initialize, build, test
      run: |
        ./crave run -- env
#    - name: Pull Build Scan
#      if: success() || failure()
#      run: |
#        mkdir gradle-user-home
#        ./crave pull -d gradle-user-home /home/admin/.gradle/build-scan-data
#    - name: Publish Build Scan
#      if: success() || failure()
#      run: ./gradlew buildScanPublishPrevious -Dgradle.user.home=gradle-user-home
